[package]
name = "bitvmx-transaction-monitor"
version = "0.1.1"
edition = "2021"
description = "Monitor"
keywords = ["bitcoin", "monitor"]
homepage = "https://github.com/FairgateLabs/rust-bitcoin-tx-monitor"
repository = "https://github.com/FairgateLabs/rust-bitcoin-tx-monitor"
readme = "README.md"


[dependencies]
bitcoin-indexer = { git = "https://github.com/FairgateLabs/rust-bitcoin-indexer", branch = "main" }
rust-bitvmx-storage-backend = { git = "https://github.com/FairgateLabs/rust-bitvmx-storage-backend", branch = "integration" }
bitcoin = "0.32.2"
bitcoincore-rpc = "0.19"
log = "0.4"
env_logger = { version = "*", default-features = false, features = [
  "termcolor",
  "atty",
  "humantime",
] }
dotenv = "0.15"
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
mockall = "0.13.0"
postgres = "0.19.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ctrlc = "3.4"

[dev-dependencies]
rand = "0.8.5"