[package]
name = "rust-bitcoin-tx-monitor"
version = "0.1.0"
edition = "2021"
description = "Monitor"
keywords = ["bitcoin", "monitor"]
homepage = "https://github.com/FairgateLabs/rust-bitcoin-tx-monitor"
repository = "https://github.com/FairgateLabs/rust-bitcoin-tx-monitor"
readme = "README.md"


[dependencies]
bitcoin = "0.32.2"
bitcoincore-rpc = "0.19"
log = "0.4"
env_logger = { version = "*", default-features = false, features = [
  "termcolor",
  "atty",
  "humantime",
] }
dotenv = "0.15"
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
