db_file_path: data

rpc:
    network: regtest
    url: http://localhost:18443
    username: user
    password: password
    wallet: test_wallet

bitvmx_file_path: bitvmx_instances_example

checkpoint_height: 1

confirmation_threshold: 6

# possible values: error | warn | info | debug | trace
rust_log: debug 

